import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderProvider } from '@/context/HeaderContext'; // Import HeaderProvider
import DynamicHeader from '@/components/DynamicHeader'; // Import DynamicHeader

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderProvider> {/* Wrap children with HeaderProvider */}
          <header className="bg-soft-blue-500 text-white p-4 shadow-md">
            <div className="container mx-auto">
              <DynamicHeader /> {/* Use DynamicHeader component */}
            </div>
          </header>
          <main className="container mx-auto p-4">{children}</main>
        </HeaderProvider>
      </body>
    </html>
  );
}
